# Generated by Django 3.1 on 2021-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheq', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='day_profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField()),
                ('team3', models.IntegerField()),
                ('team4', models.IntegerField()),
                ('roomcode', models.CharField(max_length=8)),
                ('day', models.IntegerField(max_length=1)),
            ],
        ),
    ]
